### ISSUE TITLE
Recommend reverting this back to Ruby 1.9.3 baseline given varied experience in 1.8.7

### ISSUE THREAD

**Issue by jasonhoekstra** [learningtapestry/lr-bridge#1]
Given unsuccessful experience with end-users using 1.8.7, I'd recommend rolling this back to the 1.9.3 code as a baseline supported version of Ruby.  1.8.7 syntax and gem set support is different than 1.9.3 causing challenges in maintainability going forward.

**Comment by science** [comment]
I edited the readme to reflect that 1.9.3 is supported and 1.8.7 is incidentally workable. LMK if that's insufficient.
